### ISSUE TITLE
[TODO] UI 추가 및 기타 기능

### ISSUE THREAD

**Issue by CheHyeonYeong** [greenTeaFrappe/ToyProject#50]
## 작업 상세 내용

현영
- [x] 앨범 기능 스크립트 작성
- [x] 마우스 오버기능 구현
- [x] 기능 명세서

민진
- [x] 디자인 UI 구현
요청 사항 : UI 적용 이후 이벤트 스크립트를 포함하여 기능 넣기, 0.DEMO scence를 N. SELECT-STORY (숫자는 0이 아닌 3혹은 4로 부탁드려요) 로 구현하되, scence templete로 만들어주는 형식
